# Generated by Django 4.1.2 on 2022-10-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollows',
            old_name='following_user_id',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='userfollows',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('user', 'followed_user')},
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='created',
        ),
    ]
